// File generated by flutterfire_cli.
// With modifications by developer.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMMtUtonXEVkPiRmF5SRYw2r97qUQ-yFo',
    appId: '1:501085259012:ios:f29d88121166df82563c51',
    messagingSenderId: '501085259012',
    projectId: 'tek-nightclub-app',
    // Storage bucket must use the appspot.com bucket name
    storageBucket: 'tek-nightclub-app.appspot.com',
    iosClientId: '501085259012-abcdef1234567890.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3tek',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForTesting123456789',
    appId: '1:123456789:android:abcdef1234567890',
    messagingSenderId: '123456789',
    projectId: 'tek-nightclub-app',
    storageBucket: 'tek-nightclub-app.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForTesting123456789',
    appId: '1:123456789:macos:abcdef1234567890',
    messagingSenderId: '123456789',
    projectId: 'tek-nightclub-app',
    storageBucket: 'tek-nightclub-app.appspot.com',
    iosClientId: 'your-macos-client-id.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3tek.RunnerTests',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForTesting123456789',
    appId: '1:123456789:web:abcdef1234567890',
    messagingSenderId: '123456789',
    projectId: 'tek-nightclub-app',
    storageBucket: 'tek-nightclub-app.appspot.com',
    authDomain: 'tek-nightclub-app.firebaseapp.com',
  );
}
